title: Charles Zheng EE 378b HW 6
output:
  html_document:
    mathjax: default
---

Charles Zheng EE 378b HW 6
========================================================

# Setup

Loading the data:

```{r, fig.width = 4.3, fig.height = 5}
library(Rcpp)
library(pracma)
library(magrittr)
library(RcppArmadillo)
load("~/mldata/images.RData")
imgs[1, ] %>% matrix(64, 64) %>% t %>% fliplr %>% image(col = gray(0:20/20), axes = FALSE)
```

Euclidean distance matrix

```{r}
dm <- distmat(imgs, imgs)
diag(dm) <- 0
```

# ISOMAP

Functions

```{r}
cppFunction('
NumericMatrix minplus(NumericMatrix Ar, NumericMatrix Br) {
  int n = Ar.nrow();
  int l = Ar.ncol();
  int m = Br.ncol();
  NumericMatrix ans(n, m);
  for (int i = 0; i < n; i++) {
    for (int j = 0; j < m; j++) {
      for (int k = 0; k < l; k++) {
        double x = Ar(i, k) + Br(k, j);
        if (x < ans(i, j) || k == 0) {
          ans(i, j) = x;
        }
      }
    }
  }
  return ans;
}
'
)

cppFunction('
NumericMatrix floydWarshall(NumericMatrix Ar) {
  int n = Ar.nrow();
  for (int k = 0; k < n; k++) {
    for (int i = 0; i < n; i++) {
      for (int j = 0; j < n; j++) {
        double x = Ar(i, k) + Ar(k, j);
        if (x < Ar(i, j)) {
          Ar(i, j) = x;
        }
      }
    }
  }
  return Ar;
}
'
)

knn_dist_matrix <- function(a, k) {
  for (i in 1:dim(a)[1]) {
    kthres <- sort(a[i, ])[k + 1]
    a[i, a[i, ] > kthres] <- Inf
  }
  a
}

apsp <- function(a) {
  n <- dim(a)[1]
  for (i in 1:floor(log(n)/log(2) + 1)) {
    a <- minplus(a, a)
  }
  a
}
```

Form the k-nearest neighbors distance matrix and check that it is connected.

```{r}
dm2 <- knn_dist_matrix(dm, k = 10)
proc.time()
dm3 <- floydWarshall(dm2)
proc.time()
dm3 <- apsp(dm2)
proc.time()
dm3[1, ]
sum(dm3 == Inf)
```

