# This file was generated by Rcpp::compileAttributes
# Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

rcpparma_hello_world <- function() {
    .Call('test_rcpparma_hello_world', PACKAGE = 'test')
}

rcpparma_outerproduct <- function(x) {
    .Call('test_rcpparma_outerproduct', PACKAGE = 'test', x)
}

rcpparma_innerproduct <- function(x) {
    .Call('test_rcpparma_innerproduct', PACKAGE = 'test', x)
}

rcpparma_bothproducts <- function(x) {
    .Call('test_rcpparma_bothproducts', PACKAGE = 'test', x)
}

