Matrix completion as semi-supervised regression
========================================================

Prediction using glmnet and softImpute
```{r}
library(magrittr, quietly=TRUE, warn.conflicts=FALSE)
library(pracma, quietly=TRUE, warn.conflicts=FALSE)
library(Matrix, quietly=TRUE, warn.conflicts=FALSE, verbose=FALSE)
library(foreach, quietly=TRUE, warn.conflicts=FALSE, verbose=FALSE)
library(glmnet, quietly=TRUE, warn.conflicts=FALSE, verbose=FALSE)
library(softImpute, quietly=TRUE, warn.conflicts=FALSE)
```
```{r}
glm_fit <- function(data, y_var, x_vars, tr_inds, te_inds,
                    glmnet_pars = list(), rule = "lambda.1se") {
  glmnet_pars <- modifyList(list(alpha = 0), glmnet_pars)
  y <- data[tr_inds, y_var]
  X <- as.matrix(data[tr_inds, x_vars])
  X_te <- as.matrix(data[te_inds, x_vars])
  y_te <- data[te_inds, y_var]
  glmnet_pars$y <- y
  glmnet_pars$x <- X
  fit <- do.call(cv.glmnet, glmnet_pars)
  pre <- predict(fit, X_te, s = fit[[rule]])
  cv_mse <- Norm(pre - y_te)^2/length(te_inds)
  list(fit = fit, pre = pre, cv_mse = cv_mse)
}

si_fit <- function(data, y_var, x_vars, tr_inds, te_inds,
                    si_pars = list(), yscale = 1,
                   standardize = TRUE) {
  si_pars <- modifyList(list(type = "svd", rank.max = 10), si_pars)
  #if (is.numeric(x_vars)) x_vars <- colnames(data)[x_vars]
  #if (is.numeric(y_var)) y_var <- colnames(data)[y_var]
  vars <- c(y_var, x_vars)
  X_tr <- data[c(tr_inds, te_inds), vars]
  # apply scaling
  tr_inds2 <- 1:length(tr_inds)
  te_inds2 <- max(tr_inds2) + 1:length(te_inds)
  if (standardize) {
    mus <- colMeans(X_tr[tr_inds2, ])
    sds <- apply(X_tr[tr_inds2, ], 2, sd)
    sds[1] <- sds[1]/yscale    
  }
  X_te <- X_tr
  X_tr[te_inds2, 1] <- NA
  y_te <- X_te[te_inds2, 1]
  if (standardize) {
    X_sc <- t(t(X_tr - mus)/sds)
  } else {
    X_sc <- X_tr
  }  
  si_pars$x <- X_sc
  fit <- do.call(softImpute, si_pars)
  if (standardize) {
    X_pr <- t(sds * (t(complete(X_sc, fit)) + mus))
  } else {
    X_pr <- complete(X_sc, fit)
  }
  pre <- X_pr[te_inds2, 1]
  cv_mse <- Norm(y_te - pre)^2/length(te_inds)
  list(fit = fit, pre = pre, cv_mse = cv_mse)
}
```

# Some simulation results

Generate a low-rank matrix

```{r}
n <- 5000
p <- 200
k <- 2
sigma <- 0.1
tab <- randn(n, k) %*% randn(k, p) + sigma * randn(n, p)
rperm <- sample(n, n)
n_tr <- 50
n_te <- 100
tr_inds <- rperm[1:n_tr]
te_inds <- rperm[n_tr + (1:n_te)]
y_var <- 1
x_vars <- setdiff(1:200, y_var)
```


Glmnet prediction
```{r}
# Ridge
glmnet1 <- glm_fit(tab, y_var, x_vars, tr_inds, te_inds)
(glmnet1$cv_mse)
# Lasso
glmnet2 <- glm_fit(tab, y_var, x_vars, tr_inds, te_inds, list(alpha = 1))
(glmnet2$cv_mse)
# EL 0.5
glmnet3 <- glm_fit(tab, y_var, x_vars, tr_inds, te_inds, list(alpha = 0.5))
(glmnet3$cv_mse)
```

Matrix completion
```{r}
sifit1 <- si_fit(tab, y_var, x_vars, tr_inds, te_inds, standardize = FALSE)
(sifit1$cv_mse)
sifit2 <- si_fit(tab, y_var, x_vars, tr_inds, te_inds, standardize = TRUE)
(sifit2$cv_mse)
sifit3 <- si_fit(tab, y_var, x_vars, tr_inds, te_inds, list(rank.max = 3), 
                 yscale = 1000)
(sifit3$cv_mse)
sifit4 <- si_fit(tab, y_var, x_vars, tr_inds, te_inds,
                 list(type = "als", rank.max = k), 1)
(sifit4$cv_mse)
```


