FFT vs Integration
========================================================

# Positive case

Just a function taking values for $x > 0$.
We want to obtain its Fourier transform

$$
F(\omega) = \int_0^\infty g(x) \exp(-i\omega x) dx
$$

```{r}
g <- function(x) exp(-x^2) * (x > 0)
xs <- 1:500/100
plot(xs, g(xs), type = "l")
```

Method 1: Integration (using 100 points)

```{r fig.width=7, fig.height=6}
slow_fourier <- function(f, w, len = 10, res = 100) {
  xs <- 0:(len * res)/res
  sum(f(xs) * exp(-1i * w * xs))/res
}
ws <- 0:40/20 * 2 * pi
F_slow <- sapply(ws, function(w) slow_fourier(g, w))
plot(ws, Re(F_slow), type = "l",
     ylab = expression(F(omega)), xlab = expression(omega))
```

Looks reasonable...

Method 2: Fast Fourier transform

We have

$$
\sqrt{n} F(\omega_j) = \sum_{k=1}^n g(x_k) \exp(-i x_k \omega_j)
$$
where
$$
x_k = \frac{k-1}{\sqrt{n}}
$$
$$
\omega_j = 2 \pi \frac{j-1}{\sqrt{n}}
$$

```{r}
fft_fourier <- function(f, n = 10) {
  xs <- ((1:n) - 1)/sqrt(n)
  ws <- 2 * pi * xs
  list(Fw = fft(f(xs))/sqrt(n), w = ws)
}
plot(ws, Re(F_slow), type = "l",
     ylab = expression(F(omega)), xlab = expression(omega))
res <- fft_fourier(g, 4)
lines(res$w, Re(res$Fw), col = "red")
res <- fft_fourier(g, 25)
lines(res$w, Re(res$Fw), col = "red")
res <- fft_fourier(g, 100)
lines(res$w, Re(res$Fw), col = "red")
res <- fft_fourier(g, 400)
lines(res$w, Re(res$Fw), col = "red")
res <- fft_fourier(g, 1600)
lines(res$w, Re(res$Fw), col = "red")
```

Use a different scaling.

```{r}
fft_fourier <- function(f, n = 10, alpha = 1) {
  xs <- ((1:n) - 1)/sqrt(n) * alpha
  ws <- 2 * pi * ((1:n) - 1)/sqrt(n) / alpha
  list(Fw = fft(f(xs))/sqrt(n) * alpha, w = ws)
}
plot(ws, Re(F_slow), type = "l",
     ylab = expression(F(omega)), xlab = expression(omega))
res <- fft_fourier(g, 4, 0.5)
lines(res$w, Re(res$Fw), col = "red")
res <- fft_fourier(g, 25, 0.5)
lines(res$w, Re(res$Fw), col = "red")
res <- fft_fourier(g, 100, 0.5)
lines(res$w, Re(res$Fw), col = "red")
res <- fft_fourier(g, 400, 0.5)
lines(res$w, Re(res$Fw), col = "red")
res <- fft_fourier(g, 1600, 0.5)
lines(res$w, Re(res$Fw), col = "red")
```

# Negative frequencies


Define
$$
F[f](\omega) = \int_{-\infty}^\infty f(x) \exp(-i\omega x) dx
$$

Then

$$
F[f](-\omega) = \bar{F[\bar{f}](\omega)}
$$

If the function $g$ is real: same real part, negative Im part.

```{r}
ws <- -(0:40/20 * 2 * pi)
F_slow <- sapply(ws, function(w) slow_fourier(g, w))
plot(ws, Re(F_slow), type = "l",
     ylab = expression(F(omega)), xlab = expression(omega))
res <- fft_fourier(g, 400, 0.5)
lines(-res$w, Re(res$Fw), col = "red")

plot(ws, Im(F_slow), type = "l",
     ylab = expression(F(omega)), xlab = expression(omega))
lines(-res$w, -Im(res$Fw), col = "red")
```

# Both positive and negative

Define
$$
F_+[f(x)](\omega) = \int_0^\infty f(x) \exp(-i\omega x) dx
$$

Then
$$
F[f(x)](\omega) = F_+[f(x)](\omega) + F_+[f(-x)](-\omega)
$$

```{r}
g <- function(x) exp(-x^2)
xs <- -500:500/100
plot(xs, g(xs), type = "l")
slow_fourier <- function(f, w, len = 10, res = 100) {
  xs <- (-len * res):(len * res)/res
  sum(f(xs) * exp(-1i * w * xs))/res
}
ws <- 0:40/20 * 2 * pi
F_slow <- sapply(ws, function(w) slow_fourier(g, w))
plot(ws, Re(F_slow), type = "l",
     ylab = expression(F(omega)), xlab = expression(omega))
fft_fourier2 <- function(f, n = 10, alpha = 1) {
  res <- fft_fourier(f, n, alpha)
  f2 <- function(x) { f(-x) }
  res2 <- fft_fourier(f2, n, alpha)
  Fw <- res$Fw + Conj(res2$Fw)
  ws <- res$w
  list(Fw = Fw, w = ws)
}
res <- fft_fourier2(g, 400, 0.5)
lines(res$w, Re(res$Fw), col = "red")
res <- fft_fourier2(g, 1600, 0.5)
lines(res$w, Re(res$Fw), col = "red")
```

