##

cols <- c(rgb(.7, 0, 0), rgb(0, 0, .7), rgb(.7, 0, .7))
cgrey <- rgb(0.3, 0.3, 0.3)
xs <- c(-.8, .3, .8)
zs <- rep(1:3, each = 2)
ys <- xs[zs] + c(-.3, .2, -.2, -.3, -.32, .2)
zhats <- zs; zhats[5] <- 2
yhats <- 0.9 * xs
rbind(abs(ys - yhats[1]), abs(ys - yhats[2]), abs(ys - yhats[3]))

pdf("paper/ti1.pdf")
plot(NA, NA, xlim = c(-2, 2), ylim = c(-2, 2), xlab = "x", ylab = "y")
abline(0, 1, lwd = 2)
abline(0, .9, lwd = 2, col = "red")
title("Model and fit")
legend(1.5, -1.3, c(expression(f), expression(hat(f))), lty = c(1, 1), lwd = c(2, 2), col = c("black", "red"))
dev.off()

pdf("paper/ti2.pdf")
plot(NA, NA, xlim = c(-2, 2), ylim = c(-2, 2), xlab = "x", ylab = "y", type = "l", lwd = 2)
abline(0, 1, lwd = 2)
title("Test x")
for (i in 1:3) abline(v = xs[i], col = cols[i], lwd=2)  
text(xs[1] + .13, -2, expression(x[1]), col = cols[1], cex = 2)
text(xs[2] + .13, -2, expression(x[2]), col = cols[2], cex = 2)
text(xs[3] + .13, -2, expression(x[3]), col = cols[3], cex = 2)
dev.off()

pdf("paper/ti3.pdf")
plot(NA, NA, xlim = c(-2, 2), ylim = c(-2, 2), xlab = "x", ylab = "y", type = "l", lwd = 2)
abline(0, 1, lwd = 2)
title("Test y")
for (i in 1:3) points(xs[zs[zs == i]], ys[zs == i], col = cols[i], pch = 0)
dev.off()

pdf("paper/ti4.pdf")
plot(NA, NA, xlim = c(-2, 2), ylim = c(-2, 2), xlab = "x", ylab = "y", type = "l", lwd = 2)
abline(0, 0.9, lwd = 2, col = "red")
title("Information given")
for (i in 1:3) abline(v = xs[i], col = cols[i], lwd=2)  
for (i in 1:9) abline(ys[i], 0, col = cgrey, lwd = 2)
dev.off()

pdf("paper/ti5.pdf")
plot(NA, NA, xlim = c(-2, 2), ylim = c(-2, 2), xlab = "x", ylab = "y", type = "l", lwd = 2)
abline(0, 0.9, lwd = 2, col = "red")
title(expression(paste("Estimated ", mu)))
for (i in 1:3) {
  abline(v = xs[i], col = cols[i], lwd=1, lty = 2)
}
text(xs[1], 0.9 * xs[1], expression(hat(mu)[1]), cex = 2, col = cols[1])
text(xs[2], 0.9 * xs[2], expression(hat(mu)[2]), cex = 2, col = cols[2])
text(xs[3], 0.9 * xs[3], expression(hat(mu)[3]), cex = 2, col = cols[3])
dev.off()

pdf("paper/ti6.pdf")
plot(NA, NA, xlim = c(-2, 2), ylim = c(-2, 2), xlab = "x", ylab = "y", type = "l", lwd = 2)
abline(0, 0.9, lwd = 2, col = "red")
title("Classification")
text(xs[1], 0.9 * xs[1], expression(hat(mu)[1]), cex = 2, col = cols[1])
text(xs[2], 0.9 * xs[2], expression(hat(mu)[2]), cex = 2, col = cols[2])
text(xs[3], 0.9 * xs[3], expression(hat(mu)[3]), cex = 2, col = cols[3])
for (i in 1:6) abline(ys[i], 0, col = cgrey, lwd = 2)
dev.off()

pdf("paper/ti7.pdf")
plot(NA, NA, xlim = c(-2, 2), ylim = c(-2, 2), xlab = "x", ylab = "y", type = "l", lwd = 2)
abline(0, 0.9, lwd = 2, col = "red")
title("Classification")
text(xs[1], 0.9 * xs[1], expression(hat(mu)[1]), cex = 2, col = cols[1])
text(xs[2], 0.9 * xs[2], expression(hat(mu)[2]), cex = 2, col = cols[2])
text(xs[3], 0.9 * xs[3], expression(hat(mu)[3]), cex = 2, col = cols[3])
for (i in 1:6) abline(ys[i], 0, col = cols[zhats[i]], lwd = 2)
dev.off()

pdf("paper/ti8.pdf")
plot(NA, NA, xlim = c(-2, 2), ylim = c(-2, 2), xlab = "x", ylab = "y", type = "l", lwd = 2)
abline(0, 0.9, lwd = 2, col = "red")
title("Classification")
for (i in 1:6) abline(ys[i], 0, col = cols[zhats[i]], lwd = 1, lty = 3)
for (i in 1:3) points(xs[zhats[zhats == i]], ys[zhats == i], col = cols[i], pch = 3)
dev.off()

pdf("paper/ti9.pdf")
plot(NA, NA, xlim = c(-2, 2), ylim = c(-2, 2), xlab = "x", ylab = "y", type = "l", lwd = 2)
abline(0, 1, lwd = 1)
abline(0, 0.9, lwd = 1, col = "red")
title("Misclassification")
for (i in 1:3) points(xs[zhats[zhats == i]], ys[zhats == i], col = cols[i], pch = 3)
for (i in 1:3) points(xs[zs[zs == i]], ys[zs == i], col = cols[i], pch = 0)
lines(c(xs[2:3]), rep(ys[5], 2), col = cols[3], lwd = 2)
dev.off()
